# Build-Extension.ps1
#
# Converts YoutubeAdblock.user.js into extension/main.js by:
#   1. Stripping the ==UserScript== header
#   2. Injecting GM_* -> browser-native shims inside the IIFE
#   3. Injecting event listeners that the isolated-world bridge uses
#      to relay action/command/context-menu triggers.
#
# Run after editing YoutubeAdblock.user.js. No parameters.

[CmdletBinding()]
param(
    [string]$RepoRoot,
    [string]$SourceName = 'YoutubeAdblock.user.js',
    [string]$OutDir    = 'extension',
    [string]$OutName   = 'main.js',
    [string]$NetworkRuleSource = 'extension\rules\network-rules-source.json',
    [string]$NetworkRuleOutput = 'extension\rules\network-blocks.json'
)

if ([string]::IsNullOrEmpty($RepoRoot)) {
    if ($PSScriptRoot) {
        $RepoRoot = $PSScriptRoot
    } else {
        $RepoRoot = (Get-Location).Path
    }
}

$ErrorActionPreference = 'Stop'

$srcPath = Join-Path $RepoRoot $SourceName
$outPath = Join-Path $RepoRoot (Join-Path $OutDir $OutName)
$networkSourcePath = Join-Path $RepoRoot $NetworkRuleSource
$networkOutPath = Join-Path $RepoRoot $NetworkRuleOutput

if (-not (Test-Path -LiteralPath $srcPath)) {
    throw "Source not found: $srcPath"
}

$raw = [System.IO.File]::ReadAllText($srcPath)

# Strip a leading UTF-8 BOM if present so the header regex matches cleanly.
if ($raw.Length -gt 0 -and $raw[0] -eq [char]0xFEFF) {
    $raw = $raw.Substring(1)
}

if (Test-Path -LiteralPath $networkSourcePath) {
    $networkSource = Get-Content -LiteralPath $networkSourcePath -Raw | ConvertFrom-Json
    $sourcePatterns = @($networkSource.interceptPatterns)
    $dnrRules = @($networkSource.dnrRules)
    if (-not $sourcePatterns.Count) {
        throw "Network rule source has no interceptPatterns: $networkSourcePath"
    }
    if (-not $dnrRules.Count) {
        throw "Network rule source has no dnrRules: $networkSourcePath"
    }
    foreach ($pattern in $sourcePatterns) {
        if ([string]::IsNullOrWhiteSpace([string]$pattern)) {
            throw "Network rule source contains an empty intercept pattern."
        }
        $needle = "'" + [string]$pattern + "'"
        if (-not $raw.Contains($needle)) {
            throw "Userscript DEFAULT_FILTERS.interceptPatterns missing source pattern: $pattern"
        }
    }
    $networkOutDir = Split-Path -Parent $networkOutPath
    if (-not (Test-Path -LiteralPath $networkOutDir)) {
        New-Item -ItemType Directory -Path $networkOutDir | Out-Null
    }
    $dnrJson = $dnrRules | ConvertTo-Json -Depth 30
    [System.IO.File]::WriteAllText($networkOutPath, $dnrJson + [Environment]::NewLine, (New-Object System.Text.UTF8Encoding($false)))
}

# Strip the ==UserScript== block (and anything before it that is only
# the file's leading whitespace). Case-insensitive, dotall.
$headerPattern = '(?is)^\s*//\s*==UserScript==.*?//\s*==/UserScript==\s*'
if ($raw -notmatch $headerPattern) {
    throw "Could not locate ==UserScript== header in $srcPath"
}
$body = [System.Text.RegularExpressions.Regex]::Replace($raw, $headerPattern, '', 'IgnoreCase, Singleline')

# Locate the first `'use strict';` inside the IIFE so we can inject the
# GM_* shims immediately after it. Fail loudly if the anchor moved.
$useStrictPattern = "('use strict';\s*)"
if ($body -notmatch $useStrictPattern) {
    throw "Expected 'use strict'; marker inside IIFE not found."
}

$gmShim = @'

    /* =========================================================================
     * GM_* SHIM (extension build, generated by Build-Extension.ps1)
     * =========================================================================
     * Replaces the userscript's GM_* APIs with browser-native equivalents so
     * the same source compiles into both a userscript and an MV3 extension.
     *
     * Storage strategy:
     *   - localStorage is the read path (sync, no-latency at document-start).
     *   - A CustomEvent bridge asks the ISOLATED-world content script to mirror
     *     writes into chrome.storage.local and eligible settings into
     *     chrome.storage.sync chunks. When either storage area changes (e.g.
     *     user edited settings on another signed-in browser), the bridge pushes
     *     an update back and we refresh localStorage so subsequent reads win.
     *
     * Network strategy:
     *   - GM_xmlhttpRequest -> native fetch. raw.githubusercontent.com and
     *     sponsor.ajay.app both send Access-Control-Allow-Origin: *, so
     *     MAIN-world fetch works without a background-script proxy.
     * ===================================================================== */

    const __YTAB_STORAGE_KEY = '__ytab_ext_settings__';
    const __YTAB_EVT_REQ = 'ytab:page-request';
    const __YTAB_EVT_RES = 'ytab:page-response';
    const __YTAB_EVT_SYNC = 'ytab:settings-changed';

    function __ytabReadAll() {
        try {
            const raw = localStorage.getItem(__YTAB_STORAGE_KEY);
            if (!raw) return {};
            const parsed = JSON.parse(raw);
            return (parsed && typeof parsed === 'object') ? parsed : {};
        } catch (e) {
            return {};
        }
    }

    function __ytabWriteAll(obj) {
        try {
            localStorage.setItem(__YTAB_STORAGE_KEY, JSON.stringify(obj));
        } catch (e) { /* quota / serialization failure - read path still works */ }
    }

    function __ytabMirrorToBridge(key, value) {
        try {
            const id = 'ytab-' + Math.random().toString(36).slice(2, 10);
            document.dispatchEvent(new CustomEvent(__YTAB_EVT_REQ, {
                detail: { id, op: 'set', key: __YTAB_STORAGE_KEY, value }
            }));
        } catch (e) { /* ignore */ }
    }

    function GM_getValue(key, def) {
        const all = __ytabReadAll();
        return (key in all) ? all[key] : def;
    }

    function GM_setValue(key, val) {
        const all = __ytabReadAll();
        all[key] = val;
        __ytabWriteAll(all);
        __ytabMirrorToBridge(key, all);
    }

    function GM_registerMenuCommand(_label, _fn) { return null; }
    function GM_unregisterMenuCommand(_handle) { /* no-op in extension */ }

    function GM_xmlhttpRequest(opts) {
        if (!opts || typeof opts !== 'object') return;
        const controller = (typeof AbortController !== 'undefined') ? new AbortController() : null;
        let timedOut = false;
        const timer = (opts.timeout && controller)
            ? setTimeout(() => { timedOut = true; controller.abort(); }, opts.timeout)
            : null;
        fetch(opts.url, {
            method: opts.method || 'GET',
            headers: opts.headers || undefined,
            credentials: 'omit',
            signal: controller ? controller.signal : undefined
        }).then(async (response) => {
            if (timer) clearTimeout(timer);
            let text = '';
            try { text = await response.text(); } catch (e) { text = ''; }
            if (typeof opts.onload === 'function') {
                opts.onload({
                    status: response.status,
                    statusText: response.statusText,
                    responseText: text,
                    readyState: 4
                });
            }
        }).catch((err) => {
            if (timer) clearTimeout(timer);
            if (timedOut && typeof opts.ontimeout === 'function') { opts.ontimeout(); return; }
            if (typeof opts.onerror === 'function') opts.onerror(err);
        });
    }

    // Pull cross-subdomain settings writes from the bridge into localStorage
    // so the next read wins without racing the extension storage area.
    document.addEventListener(__YTAB_EVT_SYNC, (event) => {
        const detail = event && event.detail;
        if (!detail || typeof detail !== 'object') return;
        const incoming = detail[__YTAB_STORAGE_KEY];
        if (incoming && typeof incoming === 'object') {
            try {
                localStorage.setItem(__YTAB_STORAGE_KEY, JSON.stringify(incoming));
            } catch (e) { /* ignore */ }
        } else {
            try {
                localStorage.removeItem(__YTAB_STORAGE_KEY);
            } catch (e) { /* ignore */ }
        }
    });
'@

# Inject the shim right after the first 'use strict';
$body = [System.Text.RegularExpressions.Regex]::Replace($body, $useStrictPattern, "`$1$gmShim", 'None', [System.TimeSpan]::FromSeconds(5))

# Locate the closing `})();` at the end of the IIFE and inject command hooks
# right before it. Use the last occurrence to avoid matching a nested IIFE.
$iifeClose = '})();'
$lastIdx = $body.LastIndexOf($iifeClose)
if ($lastIdx -lt 0) {
    throw "Expected closing `'})();'` of IIFE not found."
}

$commandHooks = @'

    /* ========================================================================
     * EXTENSION COMMAND HOOKS (generated by Build-Extension.ps1)
     * ======================================================================
     * Bridge DOM events dispatched from bridge.js (isolated world) into the
     * existing control functions that the userscript build exposed through
     * the Tampermonkey menu commands.
     * ==================================================================== */
    try {
        document.addEventListener('ytab:open-panel', () => {
            try { toggleSettings(true); } catch (e) { /* panel not yet built */ }
        });
        document.addEventListener('ytab:toggle-protection', () => {
            try { setScriptEnabled(!isEnabled()); } catch (e) { /* ignore */ }
        });
        document.addEventListener('ytab:refresh-rules', () => {
            try { fetchFilters(true); } catch (e) { /* ignore */ }
        });
    } catch (e) { /* DOM not ready */ }

'@

$body = $body.Substring(0, $lastIdx) + $commandHooks + $body.Substring($lastIdx)

# Prefix with a provenance header so the generated file is obviously derived.
$header = @'
/*!
 * YoutubeAdblock - extension build
 *
 * GENERATED by Build-Extension.ps1 from YoutubeAdblock.user.js.
 * Do not edit this file directly; changes will be overwritten on the next build.
 */
'@

$final = $header + "`n" + $body.TrimStart()

[System.IO.File]::WriteAllText($outPath, $final, (New-Object System.Text.UTF8Encoding($false)))

# Sanity check: the generated file must contain both shim markers AND the
# command-bridge markers. This catches regressions where a prior edit to
# the userscript moved the IIFE brace and broke injection.
$written = [System.IO.File]::ReadAllText($outPath)
$expectedMarkers = @(
    '__YTAB_STORAGE_KEY',
    'function GM_getValue',
    'function GM_xmlhttpRequest',
    "addEventListener('ytab:open-panel'",
    "addEventListener('ytab:toggle-protection'",
    "addEventListener('ytab:refresh-rules'"
)
foreach ($marker in $expectedMarkers) {
    if (-not $written.Contains($marker)) {
        throw "Generated main.js is missing required marker: $marker"
    }
}

# Basic syntax smoke-test via node if available. Failing this surfaces
# invalid JS before a user loads the broken extension.
$node = Get-Command -Name node -ErrorAction SilentlyContinue
if ($node) {
    & node --check $outPath
    if ($LASTEXITCODE -ne 0) {
        throw "node --check failed on generated main.js"
    }
}

Write-Host "Wrote $outPath ($([math]::Round((Get-Item $outPath).Length / 1024, 1)) KB)"
